# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'simplecov'
require 'simplecov-rcov'

require 'rubygems'
ENV["RAILS_ENV"] ||= "test"


def clear_data_files
  `rm -r #{APP_CONFIG['files_root']}` if Dir.exists?(APP_CONFIG['files_root'])
  `mkdir -p #{APP_CONFIG['published_rif_cs_directory']}`
  `mkdir -p #{APP_CONFIG['unpublished_rif_cs_directory']}`
  `mkdir -p #{APP_CONFIG['archived_data_directory']}`
  `find /tmp -name download_zip* -type f -exec rm -f '{}' \\; 2>/dev/null`
end

require 'cucumber/rails'
require 'ruby-debug' if ENV["RDB"]

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css
Capybara.ignore_hidden_elements = true
Capybara.server_boot_timeout = 50

# Capybara.register_driver :selenium do |app|
#   Capybara::Selenium::Driver.new(app, :browser => :chrome)
# end

`echo '' > #{Rails.root}/log/test.log`
clear_data_files

at_exit do
  clear_data_files
end

# Reset custom package_id before each test
Before do
  ActiveRecord::Base.connection.execute "ALTER SEQUENCE package_id_seq RESTART WITH 1;"
end

ActionController::Base.allow_rescue = false

begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end


require 'factory_girl_rails'
require 'cucumber/rspec/doubles'
