#!/usr/bin/ruby -w


class OCRWorker
  include Resque::Plugins::Status

  @queue = :ocr_queue

  def perform
    df = DataFile.find(options['data_file_id'])

    begin
      @total_processed = 0
      user = df.created_by

      job = Resque::Plugins::Status::Hash.get(df.uuid)
      df.transfer_status = job.status.to_s.upcase

      df.save

      Dir.mktmpdir { |dir|
        type = 'PROCESSED'
        format = 'text/plain'
        description = "This file was automatically generated by OCR. Source file name: #{df.filename}, source file id: #{df.id}"
        system *%W(tesseract #{df.path} #{dir}/#{df.filename})
        file = Rack::Test::UploadedFile.new("#{dir}/#{df.filename}.txt", format)
        builder = AttachmentBuilder.new(APP_CONFIG['files_root'], user, FileTypeDeterminer.new, MetadataExtractor.new)
        builder.build(file, df.experiment_id, type, description)
      }
      df.save

      df.mark_as_complete

    rescue Exception => e
      # Catch exception, set transfer status and rethrow so we can see what went wrong in the overview page
      df.file_processing_description = df.file_processing_description.to_s + "OCR ERROR: #{e.message}"
      df.save
      Rails.logger.info "OCR ERROR: #{e.message}"
      df.mark_as_failed
      raise e
    end
  end

end
