Date::DATE_FORMATS[:date_only] = '%Y-%m-%d'
Date::DATE_FORMATS[:with_time] = '%Y-%m-%d %k:%M'
Time::DATE_FORMATS[:with_time] = '%Y-%m-%d %k:%M'
Date::DATE_FORMATS[:with_seconds] = '%Y-%m-%d %k:%M:%S'
Time::DATE_FORMATS[:with_seconds] = '%Y-%m-%d %k:%M:%S'
