#!/bin/bash
# chkconfig: 234 20 80
# description: Tomcat Server basic start/shutdown script
# processname: tomcat
JAVA_HOME=/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/
export JAVA_HOME
TOMCAT_HOME=/usr/tomcat6/bin

case $1 in
start)
/bin/su dc21 $TOMCAT_HOME/startup.sh
;; 
stop)   
/bin/su dc21 $TOMCAT_HOME/shutdown.sh
;; 
restart)
/bin/su dc21 $TOMCAT_HOME/shutdown.sh
/bin/su dc21 $TOMCAT_HOME/startup.sh
;; 
esac    
exit 0