defaults: &defaults
  files_root: /data/dc21-data
  published_rif_cs_directory: /data/dc21-data/published_rif_cs
  unpublished_rif_cs_directory: /data/dc21-data/unpublished_rif_cs
  archived_data_directory: /data/dc21-data/archived_data
  default_readme_template_file: app/templates/file_set_metadata.html.haml
  extra_config_file_root: /data
  hiev_handle_prefix: hiev
  # the following are defaults that can be overridden in the dc21app_extra_config.yml which is kept separate from the
  # code in production servers
  notification_email_sender: noreply@intersect.org.au
  column_mappings:
    - Average Soil Temp
    - Temperature
    - Wind Speed
    - Sample
    - Rainfall
  for_codes_lookup_base_url: http://ic2-dc21-mint-vm.intersect.org.au:9001
  for_codes_path: /mint/ANZSRC_FOR/opensearch/lookup
  file_types:
    - PROCESSED
    - CLEANSED
    - UNKNOWN

  # The white list of IP addresses that are allowed to access the download page without authentication
  ip_addresses:
    - 127.0.0.1

  #IMPORTANT NOTE: the values below are only used on an initial build when database values are seeded. Modifying them later
  # will have no effect. To modify these later, you need to update the relevant rows in the database (ensuring
  # referential integrity is maintained). Refer to the user manual for details
  parameter_categories:
    -
      name: Light
      sub_categories:
        - name: Natural
        - name: Infrared
        - name: Ultraviolet
    -
      name: Atmosphere
      sub_categories:
        - name: Carbon Dioxide
        - name: Nitrogen
        - name: Oxygen
    -
      name: Temperature
      sub_categories:
        - name: Air temperature
        - name: Soil temperature
    -
      name: Humidity
      sub_categories:
        - name: Normal
    -
      name: Soil
      sub_categories:
        - name: Entisol
        - name: Vertisol
        - name: Inceptisol
        - name: Aridisol
        - name: Mollisol
        - name: Spodosol
        - name: Alfisol
        - name: Ultisol
        - name: Oxisol
        - name: Histosol
        - name: Andisols
        - name: Gelisols
    -
      name: Nutrients
      sub_categories:
        - name: Calcium
        - name: Phosphorus
    -
      name: Water
      sub_categories:
        - name: Rain water
        - name: Tap water
        - name: Distilled water

  parameter_units:
    - name: L/m2
    - name: Percentage
    - name: PPM
    - name: Degrees C
    - name: Lumens
    - name: Litres
    - name: Millilitres
    - name: Grams/Cubic Metre
    - name: Kilograms/Cubic Metre

  parameter_modifications:
    - name: Above ambient
    - name: Below ambient
    - name: Absolute target
    - name: Excluded

  tags:
    - name: Photo
    - name: Video
    - name: Gap filled


development:
  <<: *defaults

test:
  <<: *defaults
  files_root: /tmp/dc21-data/
  published_rif_cs_directory: /tmp/dc21-data/published_rif_cs
  unpublished_rif_cs_directory: /tmp/dc21-data/unpublished_rif_cs
  archived_data_directory: /tmp/dc21-data/archived_data

production:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

nectar-demo:
  <<: *defaults
