defaults: &defaults
  files_root: /data/dc21-data
  published_zip_files_directory: /data/dc21-data/published_zip_files
  published_rif_cs_directory: /data/dc21-data/published_rif_cs
  extra_config_file: /data/dc21app_extra_config.yml

development:
  <<: *defaults

test:
  <<: *defaults
  files_root: /tmp
  published_zip_files_directory: /tmp/published_zip_files
  published_rif_cs_directory: /tmp/published_rif_cs

production:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults
