parameter_categories:
  -
    name: Light
    sub_categories:
      - name: Natural
      - name: Infrared
      - name: Ultraviolet
  -
    name: Atmosphere
    sub_categories:
      - name: Carbon Dioxide
      - name: Nitrogen
      - name: Oxygen
  -
    name: Temperature
    sub_categories:
      - name: Air temperature
      - name: Soil temperature
  -
    name: Humidity
    sub_categories:
      - name: Normal
  -
    name: Soil
    sub_categories:
      - name: Entisol
      - name: Vertisol
      - name: Inceptisol
      - name: Aridisol
      - name: Mollisol
      - name: Spodosol
      - name: Alfisol
      - name: Ultisol
      - name: Oxisol
      - name: Histosol
      - name: Andisols
      - name: Gelisols
  -
    name: Nutrients
    sub_categories:
      - name: Calcium
      - name: Phosphorus
  -
    name: Water
    sub_categories:
      - name: Rain water
      - name: Tap water
      - name: Distilled water

parameter_units:
  - name: L/m2
  - name: Percentage
  - name: PPM
  - name: Degrees C
  - name: Lumens
  - name: Litres
  - name: Millilitres
  - name: Grams/Cubic Metre
  - name: Kilograms/Cubic Metre

parameter_modifications:
  - name: Above ambient
  - name: Below ambient
  - name: Absolute target
  - name: Excluded
